### ISSUE TITLE
책 p104 예제 3-2 관련 질문입니다.

### ISSUE THREAD

**Issue by Choidaewon123** [onlybooks/gamemath#4]
// 원을 구성하는 벡터를 모두 붉은색으로 표시한다.
	for (auto const& v : circles)
	{
		r.DrawPoint(v + center, LinearColor::Red);
	}

원을 구성하는 벡터를 DrawPoint 함수로 출력하는 것 같은데요. 
center라는 Vector2 형식의 변수가 없어서 혹시 currentPosition 변수의 오타가 아닌가해서 질문드립니다.

우연히 블로그 보고 공부하다가 유투브에서 책 발간하신다는 소식 듣고 구매해서 공부중입니다.
힘내세요. 감사합니다.

**Comment by ideugu** [comment]
안녕하세요. 소스 코드 변경 사항을 책에 미처 업데이트하지 못했네요.
말씀하신 부분이 맞으며 최종 소스는 여기서 확인 가능합니다.
https://github.com/onlybooks/gamemath/blob/3-2c/Source/Player/SoftRenderer2D.cpp
제보 감사합니다!

**Comment by onlybooks** [comment]
해당 내용은 이 책의 공식 정오표 페이지에 올려뒀습니다. 오류 사항 알려주셔서 고맙습니다. 추후 증쇄시에도 반영하겠습니다.
<이득우의 게임 수학> 정오표: https://www.onlybook.co.kr/entry/gamemath-errata
