### ISSUE TITLE
pg 160에 오류를 발견한 것 같습니다.

### ISSUE THREAD

**Issue by kangsangyeon** [onlybooks/gamemath#6]
안녕하세요. 며칠 전에 책 주문해서 정말 잘 읽고 있습니다!

160pg에서 아래에서 2번째 단락의 시작 부분에 오류가 있는 것 같은데요,
`**_이는 (ax + by, cx + dy)의 형식에 a = k, b = 0, c = k, d = 0 을 대입한 결과와 동일하므로.._**`
이 부분을
`**_a = k, b = 0, c = 0, d = k_**`
로 바꾸어야 하는 게 맞지 않는가 싶어 이슈 남깁니다.

**Comment by ideugu** [comment]
네 맞습니다. c=0, d=k가 되어야 합니다. 정오표에 등록해두겠습니다.
